###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.7'
services:
    redis:
        container_name: redis_bazar
        image: 'redis:alpine'
        restart: unless-stopped
        networks:
            - bazar

    mysql:
        image: 'mysql:8.0'
        container_name: bazar_mysql
        command: '--default-authentication-plugin=mysql_native_password'
        restart: unless-stopped
        working_dir: /application
        volumes:
            - './.mysql:/var/lib/mysql'
        environment:
            - MYSQL_ROOT_PASSWORD=Gjw1455
            - MYSQL_DATABASE=bazar
            - MYSQL_USER=sba
            - MYSQL_PASSWORD=Gjw1455
            - SERVICE_TAGS=dev
            - SERVICE_NAME=mysql
        ports:
            - '3308:3306'
        networks:
            - bazar

    webserver:
        container_name: nginx_bazar
        image: 'nginx:alpine'
        restart: unless-stopped
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        working_dir: /application
        volumes:
            - './app/bazar:/application'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '80:80'
        networks:
            - bazar

    php-fpm:
        container_name: php_bazar
        build: phpdocker/php-fpm
        working_dir: /application
        restart: unless-stopped
        volumes:
            - './app/bazar:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.4/fpm/conf.d/99-overrides.ini'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.4/cli/conf.d/99-overrides.ini'
        networks:
            - bazar
        depends_on:
            - mysql
            - webserver
# -----------------------------------------------
networks:
    bazar:
        driver: bridge

# -----------------------------------------------
# volumes:
#     bazar_mysql:
#         driver: local
#     bazar_nginx:
#         driver: local
#     bazar_app:
#         driver: local
#     bazar_redis:
#         driver: local
