###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.7'
services:
    ###############################################################################
    #                          REDIS
    ###############################################################################
    redis:
        container_name: redis_bazar
        image: 'redis:alpine'
        restart: unless-stopped
        networks:
            - bazar
    ###############################################################################
    #                          MYSQL
    ###############################################################################
    mysql:
        image: 'mysql:8.0'
        container_name: mysql_bazar
        command: '--default-authentication-plugin=mysql_native_password'
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - './.mysql:/var/lib/mysql'
        environment:
            - MYSQL_ROOT_PASSWORD=Gjw1455
            - MYSQL_DATABASE=bazar
            - MYSQL_USER=sba
            - MYSQL_PASSWORD=Gjw1455
            - SERVICE_TAGS=dev
            - SERVICE_NAME=mysql
        ports:
            - '3308:3306'
        networks:
            - bazar
    ###############################################################################
    #                          NGINX
    ###############################################################################
    webserver:
        container_name: nginx_bazar
        image: 'nginx:alpine'
        restart: unless-stopped
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        working_dir: /var/www
        volumes:
            - './app/bazar:/var/www:ro'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '80:80'
        networks:
            - bazar
    ###############################################################################
    #                          PHP FPM
    ###############################################################################
    php-fpm:
        container_name: php_bazar
        build: phpdocker/php-fpm
        working_dir: /var/www
        restart: unless-stopped
        volumes:
            - './app/bazar:/var/www'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.4/fpm/conf.d/99-overrides.ini'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.4/cli/conf.d/99-overrides.ini'
        networks:
            - bazar
        depends_on:
            - mysql
            - webserver
###############################################################################
#                          NETWORKS
###############################################################################
networks:
    bazar:
        driver: bridge
